feat(cspell): refine spellcheck integration & hook checks

diff --git a/pre-push b/pre-push
--- a/pre-push
+++ b/pre-push
@@ -10,6 +10,10 @@ exec 1>&2
 GITBRANCH="$(git rev-parse --abbrev-ref HEAD)"
 HOOKNAME="${0##*/}"
 GITOP="$(basename "${HOOKNAME##pre-}" .sh)"
+REPOHOME="$(pwd | sed -E "s|^$HOME|~|")"
+underline=$(tput smul) ; nounderline=$(tput rmul)
+bold=$(tput bold) ; normal=$(tput sgr0)
+
 
 if [ "gh-pages" = "$GITBRANCH" ] ; then
   echo "  git hooks $HOOKNAME ($GITBRANCH): SKIPPING tests - not a code development branch"
@@ -18,6 +22,18 @@ fi
 
 # echo something to explain lag in push
 echo "  git hooks $HOOKNAME ($GITBRANCH): running tests"
+
+## check for stale pre-push
+echo
+echo '  checking pre-push'
+if ! diff -bq ./pre-push .git/hooks/pre-push ; then
+	echo '    *** ERROR ./pre-push and active .git/hooks/pre-push differ - check failed.'
+	echo "        Try ${bold}${underline}kaleidoscope://diff?ROOT=${REPOHOME}/pre-push&REPO=${REPOHOME}/.git/hooks/pre-push&label=PRE-PUSH%20differs${nounderline}${normal}"
+	echo '        or: cp -fpv pre-push .git/hooks'
+	echo
+	exit 1
+fi
+echo
 
 ## check for package-lock.json
 [ -f package-lock.json ] || \
@@ -85,7 +101,7 @@ fi
 if hash cspell > /dev/null 2>&1 ; then
 	echo
 	echo '  Spell checking *.md LICENSE'
-	cspell *.md LICENSE || \
+	cspell ./*.md LICENSE || \
 		{ echo "  git hooks $HOOKNAME ($GITBRANCH): FAILED on 'cspell *.md'" ; exit 3 ; }
 	echo
 fi
