feat: migrate to TypeScript

diff --git a/pre-push b/pre-push
--- a/pre-push
+++ b/pre-push
@@ -80,9 +80,9 @@ echo "  git hooks $HOOKNAME ($GITBRANCH): OK, passed: 'npm run build'"
 # spell check source code if cspell available
 if hash cspell > /dev/null 2>&1 ; then
 	echo
-	echo '  Spell checking src/*.js'
-	cspell src/*.js || \
-		{ echo "  git hooks $HOOKNAME ($GITBRANCH): FAILED on 'cspell src/*.js'" ; exit 3 ; }
+	echo '  Spell checking src/*.ts'
+	cspell src/*.ts || \
+		{ echo "  git hooks $HOOKNAME ($GITBRANCH): FAILED on 'cspell src/*.ts'" ; exit 3 ; }
 	echo
 fi
 
diff --git a/preflight b/preflight
--- a/preflight
+++ b/preflight
@@ -14,9 +14,9 @@ echo
 ## check preflight (this file)
 echo '  checking preflight'
 if hash shellcheck >/dev/null 2>&1 ; then
-  shellcheck -s bash -o add-default-case -o avoid-nullary-conditions -o check-unassigned-uppercase -o deprecate-which preflight \
+  shellcheck -s sh -o add-default-case -o avoid-nullary-conditions -o check-unassigned-uppercase -o deprecate-which preflight \
     || { echo '    *** ERROR in preflight script- check failed.' ; exit 1 ; }
-  echo '    preflight: bash script OK'
+  echo '    preflight: sh script OK'
 else
   echo '    --- shellcheck not found: skipping check of preflight script.'
 fi
@@ -97,16 +97,16 @@ else
 fi
 echo
 
-## check JavaScript
-echo '  checking JavaScript w/ eslint, see .github/linters/eslint.config.js'
-npx eslint -c .github/linters/eslint.config.js "scripts/*.js" "src/*.js" ".github/linters/*.js" \
-    || { echo '    *** ERROR eslint JavaScript & JSON check failed.' ; exit 1 ; }
+## check TypeScript and JavaScript
+echo '  checking TypeScript & JavaScript w/ eslint, see .github/linters/eslint.config.js'
+npx eslint -c .github/linters/eslint.config.js "scripts/*.js" "src/*.ts" ".github/linters/*.js" \
+    || { echo '    *** ERROR eslint TypeScript & JavaScript check failed.' ; exit 1 ; }
 if hash cspell >/dev/null 2>&1 ; then
   printf '  '
-	cspell src/*.js || \
-		{ echo '    *** ERROR "cspell src/*.js" failed.' ; exit 1 ; }
+	cspell src/*.ts || \
+		{ echo '    *** ERROR "cspell src/*.ts" failed.' ; exit 1 ; }
 fi
-echo '    scripts/*.js, src/*.js, .github/linters/*.js: JavaScript OK'
+echo '    scripts/*.js, src/*.ts, .github/linters/*.js: TypeScript & JavaScript OK'
 echo
 
 echo '  OK, preflight checks passed.'
